language: ruby
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.1
  - ruby-2.4.0
gemfile:
  - Gemfile.travis
script:
  - bundle exec rubocop
  - bundle exec rspec spec
sudo: false
before_install:
  - gem update --system
  - gem update bundler
